/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package casino;

import java.io.FileWriter;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

/**
 *
 * @author ldjet
 */
public class EnterDetailsGUI extends javax.swing.JFrame {

    /**
     * Creates new form EnterDetailsGUI
     */
    public EnterDetailsGUI() {
        initComponents();
    }
    
    public void ModeChange(String Mode){
        
        DetailsButton.setText(Mode);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EnterDetailsPanel = new javax.swing.JPanel();
        Title1 = new javax.swing.JLabel();
        NewUsernameField = new javax.swing.JTextField();
        NewPasswordField = new javax.swing.JPasswordField();
        UsernameEnterLabel = new javax.swing.JLabel();
        UsernameEnterLabel1 = new javax.swing.JLabel();
        DetailsButton = new javax.swing.JButton();
        StatusLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(257, 333));

        EnterDetailsPanel.setAlignmentY(0.0F);
        EnterDetailsPanel.setMaximumSize(new java.awt.Dimension(257, 333));
        EnterDetailsPanel.setMinimumSize(new java.awt.Dimension(257, 333));

        Title1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 36)); // NOI18N
        Title1.setForeground(new java.awt.Color(153, 0, 204));
        Title1.setText("ROYAL CASINO");
        Title1.setAlignmentX(0.5F);

        NewUsernameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NewUsernameField.setToolTipText("Enter Username");
        NewUsernameField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        NewUsernameField.setMaximumSize(new java.awt.Dimension(185, 37));
        NewUsernameField.setMinimumSize(new java.awt.Dimension(185, 37));
        NewUsernameField.setPreferredSize(new java.awt.Dimension(185, 37));

        NewPasswordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NewPasswordField.setToolTipText("Enter Password");
        NewPasswordField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        NewPasswordField.setMaximumSize(new java.awt.Dimension(185, 37));
        NewPasswordField.setMinimumSize(new java.awt.Dimension(185, 37));
        NewPasswordField.setPreferredSize(new java.awt.Dimension(185, 37));
        NewPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewPasswordFieldActionPerformed(evt);
            }
        });

        UsernameEnterLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UsernameEnterLabel.setText("Enter Username:");

        UsernameEnterLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UsernameEnterLabel1.setText("Enter Password:");

        DetailsButton.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        DetailsButton.setBorder(null);
        DetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetailsButtonActionPerformed(evt);
            }
        });

        StatusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout EnterDetailsPanelLayout = new javax.swing.GroupLayout(EnterDetailsPanel);
        EnterDetailsPanel.setLayout(EnterDetailsPanelLayout);
        EnterDetailsPanelLayout.setHorizontalGroup(
            EnterDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnterDetailsPanelLayout.createSequentialGroup()
                .addGroup(EnterDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EnterDetailsPanelLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(UsernameEnterLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EnterDetailsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Title1))
                    .addGroup(EnterDetailsPanelLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(DetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EnterDetailsPanelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(UsernameEnterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EnterDetailsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(EnterDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(StatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NewPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NewUsernameField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );
        EnterDetailsPanelLayout.setVerticalGroup(
            EnterDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnterDetailsPanelLayout.createSequentialGroup()
                .addComponent(Title1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(UsernameEnterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NewUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UsernameEnterLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NewPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(StatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EnterDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EnterDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewPasswordFieldActionPerformed

    private void DetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetailsButtonActionPerformed
        if (Casino.WelcomeMode.equals("Register")) {
            
            try{
            
            JSONObject Data = (JSONObject) (new JSONParser().parse(Casino.GetJson()));
            
            JSONObject Users = (JSONObject) Data.get("Users");
            
            JSONObject NewUser = new JSONObject();
            
            NewUser.put("Password", NewPasswordField.getText());
            NewUser.put("Balance", "100");
            
            Users.put(NewUsernameField.getText(), NewUser);
            
            System.out.println(Data.toJSONString());
            
            FileWriter file = new FileWriter("Data.json");
            
            file.write(Data.toJSONString());
            file.flush();
            
            StatusLabel.setText("Account created - Redirecting");
            
            Casino.LoadMainMenu(NewUsernameField.getText(), 100);
            
            }catch(Exception e){
            System.out.println(e);
            }
        }else{
            
            JSONObject User = Casino.GetUser(NewUsernameField.getText());
            
            if(User == null){
                StatusLabel.setText("Error: Account not found");
                return;
            }
        
            String CorrectPassword = (String) User.get("Password");
            
            if (CorrectPassword.equals(NewPasswordField.getText())) {
                StatusLabel.setText("Logged in - Redirecting");
                Casino.LoadMainMenu(NewUsernameField.getText(), Integer.parseInt((String) User.get("Balance")));

            }else{
                StatusLabel.setText("Error: Incorrect Password");
            }

        }
        
    }//GEN-LAST:event_DetailsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnterDetailsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnterDetailsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnterDetailsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnterDetailsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnterDetailsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DetailsButton;
    private javax.swing.JPanel EnterDetailsPanel;
    private javax.swing.JPasswordField NewPasswordField;
    private javax.swing.JTextField NewUsernameField;
    private javax.swing.JLabel StatusLabel;
    private javax.swing.JLabel Title1;
    private javax.swing.JLabel UsernameEnterLabel;
    private javax.swing.JLabel UsernameEnterLabel1;
    // End of variables declaration//GEN-END:variables
}
