/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package casino;

import java.awt.Image;
import java.util.Random;
import javax.swing.ImageIcon;

public class HigherLowerGUI extends javax.swing.JFrame {

    private static String[] cardFace = {"A", "2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K"};
    private static String[] suit = {"D", "H", "S", "C"};
    
    private static int[]  HigherOdds = {0,5,5,5,5,10,15,20,25,30,40,50,0};
    private static int[] LowerOdds = {0,50,40,30,25,20,15,10,5,5,5,5,0};

    private String CurrCard = "";
    private int Balance = 0;
    

    public HigherLowerGUI() {
        initComponents();

        Random random = new Random();

        CurrCard = getNextCard();

    }
    
    public void UpdateBalance(int NewBalance){ // Only local sided to this game
        
        BalanceTitle.setText("Balance: "+NewBalance);
        Balance = NewBalance; // Not always used but :/
    }

    public String getNextCard() {

        Random random = new Random();

        String Card = cardFace[random.nextInt(13)] + suit[random.nextInt(4)];

        ImageIcon CardImg = new javax.swing.ImageIcon(getClass().getResource("cards\\" + Card + ".png"));

        CurCard.setIcon(new ImageIcon(CardImg.getImage().getScaledInstance(170, 240, Image.SCALE_DEFAULT)));

        return Card;
    }

    public int getFaceInt(String Card) {

        String CardFFace = "" + Card.charAt(0);
        int pos = 0;

        for (int i = 0; i < 13; i++) {

            if (cardFace[i].equals(CardFFace)) {
                pos = i;
                break;

            }

        }
        return pos;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        CurCard = new javax.swing.JLabel();
        HigherB = new javax.swing.JButton();
        LowerB = new javax.swing.JButton();
        StatusTitle = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BalanceTitle = new javax.swing.JLabel();
        ReturnB = new javax.swing.JButton();
        QuestionTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(1, 1, 1));
        setMaximumSize(new java.awt.Dimension(500, 309));
        setMinimumSize(new java.awt.Dimension(500, 309));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 309));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 204));
        jLabel2.setText("Current Card:");

        CurCard.setMaximumSize(new java.awt.Dimension(135, 200));
        CurCard.setPreferredSize(new java.awt.Dimension(135, 200));

        HigherB.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        HigherB.setText("Higher");
        HigherB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HigherBActionPerformed(evt);
            }
        });

        LowerB.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        LowerB.setText("Lower");
        LowerB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LowerBActionPerformed(evt);
            }
        });

        StatusTitle.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        StatusTitle.setForeground(new java.awt.Color(153, 0, 204));
        StatusTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StatusTitle.setText(" ");

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 204));
        jLabel3.setText("Next Card:");

        BalanceTitle.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        BalanceTitle.setForeground(new java.awt.Color(153, 0, 204));
        BalanceTitle.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        BalanceTitle.setText("Balance: 0");

        ReturnB.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        ReturnB.setText("Return");
        ReturnB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnBActionPerformed(evt);
            }
        });

        QuestionTitle.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        QuestionTitle.setForeground(new java.awt.Color(153, 0, 204));
        QuestionTitle.setText("25 coins per play");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CurCard, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(QuestionTitle)))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BalanceTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addComponent(ReturnB))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(HigherB, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(LowerB, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(StatusTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CurCard, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ReturnB)
                        .addGap(35, 35, 35)
                        .addComponent(HigherB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(StatusTitle)
                        .addGap(18, 18, 18)
                        .addComponent(LowerB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(QuestionTitle)
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BalanceTitle)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HigherBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HigherBActionPerformed
        StatusTitle.setText(" ");
        
        if(Balance > 25){
            
            String NewCard = getNextCard();

            if (getFaceInt(NewCard) > getFaceInt(CurrCard)) {

                Balance = Balance + HigherOdds[getFaceInt(CurrCard)];
                UpdateBalance(Balance);
                StatusTitle.setText("Correct! +" +HigherOdds[getFaceInt(CurrCard)]+" coins!");
                
            }else if(getFaceInt(NewCard) == getFaceInt(CurrCard)){
                
                UpdateBalance(Balance);
                StatusTitle.setText("Draw! +0 coins!");
                
            }else {
                Balance = Balance - 25;
                UpdateBalance(Balance);
                StatusTitle.setText("Incorrect!");
            }

            CurrCard = NewCard; 
        }else{
            StatusTitle.setText("Not enough coins to play!");
        }
        
        

    }//GEN-LAST:event_HigherBActionPerformed

    private void LowerBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LowerBActionPerformed
        StatusTitle.setText(" ");
        
        if(Balance > 25){
            
            String NewCard = getNextCard();

            if (getFaceInt(NewCard) < getFaceInt(CurrCard)) {

                Balance = Balance + LowerOdds[getFaceInt(CurrCard)];
                UpdateBalance(Balance);
                StatusTitle.setText("Correct! +" +LowerOdds[getFaceInt(CurrCard)]+" coins!");
                
            }else if(getFaceInt(NewCard) == getFaceInt(CurrCard)){
                
                UpdateBalance(Balance);
                StatusTitle.setText("Draw! +0 coins!");
                
            }else {
                Balance = Balance - 25;
                UpdateBalance(Balance);
                StatusTitle.setText("Incorrect!");
            }

            CurrCard = NewCard; 
        }else{
            StatusTitle.setText("Not enough coins to play!");
        }



    }//GEN-LAST:event_LowerBActionPerformed

    private void ReturnBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnBActionPerformed
        Casino.UnloadGames(Balance);
    }//GEN-LAST:event_ReturnBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HigherLowerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HigherLowerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HigherLowerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HigherLowerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HigherLowerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BalanceTitle;
    private javax.swing.JLabel CurCard;
    private javax.swing.JButton HigherB;
    private javax.swing.JButton LowerB;
    private javax.swing.JLabel QuestionTitle;
    private javax.swing.JButton ReturnB;
    private javax.swing.JLabel StatusTitle;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
