/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package casino;

/**
 *
 * @author ldjet
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }
    
    public void UpdateInfo(String Username, String Balance){
        
        WelcomeTitle.setText("Welcome, "+Username+"!");
        BalanceTitle.setText("Balance: "+Balance);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WelcomeTitle = new javax.swing.JLabel();
        QuestionTitle = new javax.swing.JLabel();
        HigherOrLowerB = new javax.swing.JButton();
        BlackjackB = new javax.swing.JButton();
        SlotsB = new javax.swing.JButton();
        BalanceTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 309));
        setMinimumSize(new java.awt.Dimension(500, 309));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 309));

        WelcomeTitle.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 28)); // NOI18N
        WelcomeTitle.setForeground(new java.awt.Color(153, 0, 204));
        WelcomeTitle.setText("Welcome, user!");

        QuestionTitle.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        QuestionTitle.setForeground(new java.awt.Color(153, 0, 204));
        QuestionTitle.setText("What game do you want to play?");

        HigherOrLowerB.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        HigherOrLowerB.setText("Higher or Lower");
        HigherOrLowerB.setBorder(null);
        HigherOrLowerB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HigherOrLowerBActionPerformed(evt);
            }
        });

        BlackjackB.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        BlackjackB.setText("Blackjack");
        BlackjackB.setBorder(null);
        BlackjackB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlackjackBActionPerformed(evt);
            }
        });

        SlotsB.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        SlotsB.setText("Slot Machine");
        SlotsB.setBorder(null);
        SlotsB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SlotsBActionPerformed(evt);
            }
        });

        BalanceTitle.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        BalanceTitle.setForeground(new java.awt.Color(153, 0, 204));
        BalanceTitle.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        BalanceTitle.setText("Balance: 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WelcomeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QuestionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HigherOrLowerB, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BlackjackB, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SlotsB, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(183, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BalanceTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WelcomeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QuestionTitle)
                .addGap(40, 40, 40)
                .addComponent(HigherOrLowerB, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BlackjackB, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SlotsB, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BalanceTitle)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HigherOrLowerBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HigherOrLowerBActionPerformed
        Casino.LoadHigherOrLower();
    }//GEN-LAST:event_HigherOrLowerBActionPerformed

    private void BlackjackBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlackjackBActionPerformed
        Casino.LoadBlackJack();
    }//GEN-LAST:event_BlackjackBActionPerformed

    private void SlotsBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SlotsBActionPerformed

    }//GEN-LAST:event_SlotsBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BalanceTitle;
    private javax.swing.JButton BlackjackB;
    private javax.swing.JButton HigherOrLowerB;
    private javax.swing.JLabel QuestionTitle;
    private javax.swing.JButton SlotsB;
    private javax.swing.JLabel WelcomeTitle;
    // End of variables declaration//GEN-END:variables
}
